import { Component, OnInit } from '@angular/core';

interface FeederRow {
  feedertype: string;
  on: number;
  tf: number;
  sf: number;
  instatus: string; // dot icons
}

@Component({
  selector: 'app-feeder',
  templateUrl: './feeder.component.html',
  styleUrls: ['./feeder.component.css'],
})
export class FeederComponent {
  result: { [feedertype: string]: FeederRow } = {};
  feederinfo: any[] = [
    {
      Id: 106,
      substationId: 10,
      Name: '66kV TR-1',
      PTR: 89,
      CTR: 278,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 0,
      Type: 35,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '',
      CTPTRating: '',
      MVARating: '3',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '42',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 1,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '106',
      Did: '4994460968761198439',
      IsIMPforloss: true,
      IsActive: true,
      IsSubtraction: true,
      Fdr_Code: '10114001',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 290,
      Feeder_Make: 52,
      Eqt_Code: 133,
      Eqt_No: 1,
      fdr_code1: '',
      BMU_Serial_No: '2303-1-66-T-23',
      bmu_Reference_BMUId: 1,
      bmu_Embedded_BMU_Id: 1,
      bmu_SlaveID: 101,
      bmu_DHCP: '106',
      bmu_SLA_VD: '108',
      bmu_Analytics_VD: '123',
      BMU_IP_Address: '192.168.0.101',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: '2024-10-31T00:00:00',
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 108,
      substationId: 10,
      Name: '66kV TR-2',
      PTR: 89,
      CTR: 278,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 0,
      Type: 35,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '',
      CTPTRating: '',
      MVARating: '3',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '42',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 2,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '108',
      Did: '4994460968761198439',
      IsIMPforloss: true,
      IsActive: true,
      IsSubtraction: true,
      Fdr_Code: '10114002',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 54,
      Eqt_Code: 133,
      Eqt_No: 2,
      fdr_code1: '',
      BMU_Serial_No: '2303-1-66-T-19',
      bmu_Reference_BMUId: 2,
      bmu_Embedded_BMU_Id: 2,
      bmu_SlaveID: 2,
      bmu_DHCP: '106',
      bmu_SLA_VD: '109',
      bmu_Analytics_VD: '123',
      BMU_IP_Address: '192.168.0.102',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: '2024-11-30T00:00:00',
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 111,
      substationId: 10,
      Name: '66kV UNAVA PETHAPUR LINE',
      PTR: 89,
      CTR: 280,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 0,
      Type: 36,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '',
      CTPTRating: '',
      MVARating: '36',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '42',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 1,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '111',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: false,
      Fdr_Code: '10114003',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 54,
      Eqt_Code: 134,
      Eqt_No: 1,
      fdr_code1: '',
      BMU_Serial_No: '2303-1-66-T-13',
      bmu_Reference_BMUId: 3,
      bmu_Embedded_BMU_Id: 3,
      bmu_SlaveID: 3,
      bmu_DHCP: '106',
      bmu_SLA_VD: '110',
      bmu_Analytics_VD: '123',
      BMU_IP_Address: '192.168.0.103',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: '2024-12-31T00:00:00',
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 112,
      substationId: 10,
      Name: '66k UNAVA ITLA',
      PTR: 89,
      CTR: 280,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 0,
      Type: 36,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '',
      CTPTRating: '',
      MVARating: '36',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '42',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 2,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '112',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: false,
      Fdr_Code: '10114004',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 54,
      Eqt_Code: 134,
      Eqt_No: 2,
      fdr_code1: '',
      BMU_Serial_No: '2303-1-66-T-15',
      bmu_Reference_BMUId: 4,
      bmu_Embedded_BMU_Id: 4,
      bmu_SlaveID: 4,
      bmu_DHCP: '106',
      bmu_SLA_VD: '111',
      bmu_Analytics_VD: '123',
      BMU_IP_Address: '192.168.0.104',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: null,
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 114,
      substationId: 10,
      Name: '11kV INCOMER ',
      PTR: 88,
      CTR: 94,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 0,
      Type: 37,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '',
      CTPTRating: '',
      MVARating: '5',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '41',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 1,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '114',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: true,
      Fdr_Code: '10114005',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 49,
      Eqt_Code: 135,
      Eqt_No: 1,
      fdr_code1: '',
      BMU_Serial_No: '2303-1-11-T-42',
      bmu_Reference_BMUId: 5,
      bmu_Embedded_BMU_Id: 5,
      bmu_SlaveID: 5,
      bmu_DHCP: '106',
      bmu_SLA_VD: '112',
      bmu_Analytics_VD: '124',
      BMU_IP_Address: '192.168.0.105',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: null,
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 115,
      substationId: 10,
      Name: '11kV INCOMER 2',
      PTR: 88,
      CTR: 95,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 0,
      Type: 37,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '',
      CTPTRating: '',
      MVARating: '10',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '41',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 2,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '115',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: true,
      Fdr_Code: '10114006',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 49,
      Eqt_Code: 135,
      Eqt_No: 2,
      fdr_code1: '',
      BMU_Serial_No: '2312-22-11-T-13787',
      bmu_Reference_BMUId: 6,
      bmu_Embedded_BMU_Id: 6,
      bmu_SlaveID: 6,
      bmu_DHCP: '106',
      bmu_SLA_VD: '113',
      bmu_Analytics_VD: '124',
      BMU_IP_Address: '192.168.0.106',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: null,
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 119,
      substationId: 10,
      Name: '11kV STATION TR',
      PTR: 88,
      CTR: 94,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 0,
      Type: 38,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '4',
      CTPTRating: '',
      MVARating: '5',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '41',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 1,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '119',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: true,
      Fdr_Code: '10114008',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 49,
      Eqt_Code: 136,
      Eqt_No: 1,
      fdr_code1: '15775',
      BMU_Serial_No: '2303-1-11-C-8',
      bmu_Reference_BMUId: 8,
      bmu_Embedded_BMU_Id: 8,
      bmu_SlaveID: 8,
      bmu_DHCP: '106',
      bmu_SLA_VD: '115',
      bmu_Analytics_VD: '124',
      BMU_IP_Address: '192.168.0.108',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: null,
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 121,
      substationId: 10,
      Name: '11kV CAPACITOR BANK',
      PTR: 88,
      CTR: 93,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 0,
      Type: 39,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '',
      CTPTRating: '',
      MVARating: '8',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '41',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 1,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '121',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: false,
      Fdr_Code: '10114009',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 49,
      Eqt_Code: 137,
      Eqt_No: 1,
      fdr_code1: '',
      BMU_Serial_No: '2303-1-11-C-22',
      bmu_Reference_BMUId: 9,
      bmu_Embedded_BMU_Id: 9,
      bmu_SlaveID: 9,
      bmu_DHCP: '106',
      bmu_SLA_VD: '116',
      bmu_Analytics_VD: '124',
      BMU_IP_Address: '192.168.0.109',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: null,
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 123,
      substationId: 10,
      Name: '11kV MAHADEV ',
      PTR: 88,
      CTR: 94,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 2,
      Type: 40,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '68',
      CTPTRating: '',
      MVARating: '5',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '41',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 1,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '123',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: true,
      Fdr_Code: '10114010',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 49,
      Eqt_Code: 138,
      Eqt_No: 1,
      fdr_code1: '15774',
      BMU_Serial_No: '2303-1-11-T-105',
      bmu_Reference_BMUId: 10,
      bmu_Embedded_BMU_Id: 10,
      bmu_SlaveID: 10,
      bmu_DHCP: '106',
      bmu_SLA_VD: '117',
      bmu_Analytics_VD: '125',
      BMU_IP_Address: '192.168.0.110',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: null,
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 124,
      substationId: 10,
      Name: '11kV VIR MAHARAJA ',
      PTR: 88,
      CTR: 94,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 2,
      Type: 40,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '73',
      CTPTRating: '',
      MVARating: '5',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '41',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 2,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '124',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: true,
      Fdr_Code: '10114011',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 49,
      Eqt_Code: 138,
      Eqt_No: 2,
      fdr_code1: '16038',
      BMU_Serial_No: '2303-1-11-T-99',
      bmu_Reference_BMUId: 11,
      bmu_Embedded_BMU_Id: 11,
      bmu_SlaveID: 11,
      bmu_DHCP: '106',
      bmu_SLA_VD: '118',
      bmu_Analytics_VD: '125',
      BMU_IP_Address: '192.168.0.111',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: null,
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 126,
      substationId: 10,
      Name: '11kV JOGMAYA ',
      PTR: 88,
      CTR: 94,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 2,
      Type: 40,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '65',
      CTPTRating: '',
      MVARating: '5',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '41',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 3,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '126',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: true,
      Fdr_Code: '10114012',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 49,
      Eqt_Code: 138,
      Eqt_No: 3,
      fdr_code1: '15772',
      BMU_Serial_No: '2303-1-11-T-89',
      bmu_Reference_BMUId: 12,
      bmu_Embedded_BMU_Id: 12,
      bmu_SlaveID: 12,
      bmu_DHCP: '106',
      bmu_SLA_VD: '119',
      bmu_Analytics_VD: '126',
      BMU_IP_Address: '192.168.0.112',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: null,
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 128,
      substationId: 10,
      Name: '11kV SHAKTINAGAR',
      PTR: 88,
      CTR: 93,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 2,
      Type: 40,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '50',
      CTPTRating: '',
      MVARating: '3',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '41',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 4,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '128',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: true,
      Fdr_Code: '10114013',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 49,
      Eqt_Code: 138,
      Eqt_No: 4,
      fdr_code1: '15771',
      BMU_Serial_No: '2303-1-11-T-100',
      bmu_Reference_BMUId: 13,
      bmu_Embedded_BMU_Id: 13,
      bmu_SlaveID: 13,
      bmu_DHCP: '106',
      bmu_SLA_VD: '120',
      bmu_Analytics_VD: '126',
      BMU_IP_Address: '192.168.0.113',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: null,
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 129,
      substationId: 10,
      Name: '11kV MAHAKALI ',
      PTR: 88,
      CTR: 94,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 1,
      Type: 40,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '2621',
      CTPTRating: '',
      MVARating: '5',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '41',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 5,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '129',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: true,
      Fdr_Code: '10114014',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 49,
      Eqt_Code: 138,
      Eqt_No: 5,
      fdr_code1: '15773',
      BMU_Serial_No: '2303-1-11-T-15',
      bmu_Reference_BMUId: 14,
      bmu_Embedded_BMU_Id: 14,
      bmu_SlaveID: 14,
      bmu_DHCP: '106',
      bmu_SLA_VD: '121',
      bmu_Analytics_VD: '127',
      BMU_IP_Address: '192.168.0.114',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: null,
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 131,
      substationId: 10,
      Name: '11kV TIRUPATI ',
      PTR: 88,
      CTR: 94,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 1,
      Type: 40,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '1373',
      CTPTRating: '',
      MVARating: '5',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '41',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 6,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '131',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: true,
      Fdr_Code: '10114015',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 49,
      Eqt_Code: 138,
      Eqt_No: 6,
      fdr_code1: '15770',
      BMU_Serial_No: '2303-1-11-T-102',
      bmu_Reference_BMUId: 15,
      bmu_Embedded_BMU_Id: 15,
      bmu_SlaveID: 15,
      bmu_DHCP: '106',
      bmu_SLA_VD: '122',
      bmu_Analytics_VD: '127',
      BMU_IP_Address: '192.168.0.115',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: null,
      IsRDSS: false,
      isADMS: false,
    },
    {
      Id: 117,
      substationId: 10,
      Name: '11kV BUS COUPLER',
      PTR: 88,
      CTR: 0,
      CommissionDate: '2024-01-01T00:00:00',
      Category: 0,
      Type: 274,
      C11KVLineLen: '',
      LTLineLen: '',
      TTLConsumers: '',
      CTPTRating: '',
      MVARating: '1',
      TTLContractedLoad: '',
      SubStation: '66kV UNAVA  SS',
      D_SubNock: 'GUVNL',
      D_Discome: 'UGVCL',
      D_Region: 'REGION1',
      D_Zone: 'ZONE1',
      D_Circle: 'SABARMATI',
      D_Division: 'Gandhinagar (Rural)',
      Voltage_Levels: '41',
      D_SubDivision: 'Gandhinagar',
      G_SubNock: 'GUJARAT',
      G_Zone: 'MEHSANA',
      G_Circle: 'HIMMATANAGAR',
      G_Division: 'JAMLA',
      G_Subdivision: null,
      D_SubNock_Id: 1,
      D_Discome_Id: 1,
      D_Region_id: 1,
      D_Zone_id: 1,
      D_Circle_id: 4,
      D_Division_id: 13,
      D_SubDivision_id: 21,
      G_SubNock_id: 2,
      G_Zone_id: 2,
      G_Circle_id: 2,
      G_Division_id: 2,
      Sequence: 1,
      Sld_Sequence: -1,
      IMEI: '863963065379237',
      Location: '117',
      Did: '4994460968761198439',
      IsIMPforloss: false,
      IsActive: true,
      IsSubtraction: false,
      Fdr_Code: '10114007',
      TR_Manufactur_Date: null,
      Fdr_mfg_year: 0,
      TR_make: 0,
      Feeder_Make: 49,
      Eqt_Code: 139,
      Eqt_No: 1,
      fdr_code1: '',
      BMU_Serial_No: '2303-1-11-C-14',
      bmu_Reference_BMUId: 7,
      bmu_Embedded_BMU_Id: 7,
      bmu_SlaveID: 7,
      bmu_DHCP: '106',
      bmu_SLA_VD: '114',
      bmu_Analytics_VD: '124',
      BMU_IP_Address: '192.168.0.107',
      MCU_Id: 30,
      MCU_Number: 1,
      DischargeDate: null,
      IsRDSS: false,
      isADMS: false,
    },
  ];

  typeMap: any = {
    '35': { key: 'T', label: '66 KV Tr.' },
    '36': { key: 'L', label: '66 KV Line' },
    '37': { key: 'I', label: '11 KV Incomer' },
    '38': { key: 'S', label: 'Station Tr.' },
    '39': { key: 'C', label: 'Cap Bank' },
    '274': { key: 'B', label: 'Bus Coupler' },
    '40': { key: 'D', label: 'Distributer' },
  };

  categoryMap: any = {
    1: 'Rural (JGY)',
    2: 'Agriculture',
    3: 'Urban',
    4: 'AG Solar',
    5: 'HT Express',
    8: 'Industrial',
    9: 'Solar',
  };

  statusColors: any = {
    1: '🔴', // On
    2: '🟡', // TT
    3: '🟢', // SF
    4: '🔴', // On
  };

  feederStatus: { [nm: string]: number } = {
    'T-1-FDNST': 1,
    'T-2-FDNST': 2,
    'D-1-FDNST': 1,
    'D-2-FDNST': 3,
    'L-1-FDNST': 1,
    'L-2-FDNST': 1,
    'D-3-FDNST': 1,
    'D-4-FDNST': 1,
    'D-5-FDNST': 1,
    'D-6-FDNST': 1,
    'S-1-FDNST': 1,
    'C-1-FDNST': 1,
    'B-1-FDNST': 1,
    'I-1-FDNST': 1,
    'I-2-FDNST': 1,
  };

  ngOnInit() {
    this.processFeederInfo();
  }

  processFeederInfo() {
    this.result = {};
    this.feederinfo.forEach((item: any) => {
      const type = String(item.Type);
      const seq = item.Sequence;
      const cat = item.Category;

      const typeInfo = this.typeMap[type];
      if (!typeInfo) return;

      let feedertype = typeInfo.label;

      if (type === '40') {
        feedertype = this.categoryMap[cat] || 'Distributer';
      }

      const key = `${typeInfo.key}-${seq}-FDNST`;
      const status = this.feederStatus[key];
      const statusDot = this.statusColors[status] || '';

      if (!this.result[feedertype]) {
        this.result[feedertype] = {
          feedertype,
          on: 0,
          tf: 0,
          sf: 0,
          instatus: '',
        };
      }

      const row = this.result[feedertype];
      if (status === 1 || status === 4) row.on++;
      else if (status === 2) row.tf++;
      else if (status === 3) row.sf++;

      row.instatus += statusDot + ' ';
    });
  }

  get resultArray(): FeederRow[] {
    return Object.values(this.result);
  }

  get allFeederTypes(): string[] {
    const baseTypes = Object.values(this.typeMap).map((t:any) => t.label);
    const categoryTypes = Object.values(this.categoryMap); // for type 40

    const all = [...baseTypes, ...categoryTypes];
    return [...new Set(all)]; // ensure unique
  }
}
